version: '3.3'

services:
  db:
    container_name: "db"
    image: mongo
    ports:
      - "27017:27017"

  server:
    container_name: "server"
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - ENV=DEV
      - HOST=0.0.0.0
      - PORT=8000
      - MONGODB_CLOUD_URI=
      - MONGODB_LOCAL_URI=mongodb://db:27017/
      - FRONTEND_HOST=http://localhost:3000
      - JWT_SECRET=token
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: 'bitnami/redis:latest'
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

